' Gambas class file

' GambasCAD
' A simple CAD made in Gambas
'
' Copyright (C) Ing Martin P Cristia
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
Create Static
'Fast
Inherits CadPoint

Public Const Gender As String = "VERTEX"
Public Const DrawingOrder As Integer = 1        ' 1 = draws first
Public Const CmdLineHelper As String = ("a 3D point")
Public Const ParamType As String = "P"                             ' that is Point, Point; could be Color Text, etc
Public Const ParamHelper As String = "Point"
Public Const GAMBASCADENTITY As String = "EntityBase"
Public Const USEWITH As String = "ENTITYBUILDER"

' fParam helpers
Public Const TotalParams As Integer = 10
Public Const ipaWIdthStart40 As Integer = 0
Public Const ipaWIdthEnd41 As Integer = 1
Public Const ipaBulge42 As Integer = 2
Public Const ipaFlags70 As Integer = 3
Public Const ipaCurveDiection50 As Integer = 4
Public Const ipaMeshIndex1_71 As Integer = 5
Public Const ipaMeshIndex2_72 As Integer = 6
Public Const ipaMeshIndex3_73 As Integer = 7
Public Const ipaMeshIndex4_74 As Integer = 8
Public Const ipaIdentifier91 As Integer = 9

Public Sub ExportDXFCol(e As Entity, ByRef stxExport As String[]) As Boolean

    ' stxExport.insert(["VERTEX", dxf.codEntity])
    ' Los datos comunes a todas las entidades son guardados por la rutina que llama a esta
    stxExport.insert(["AcDbPoint", "100"])
    stxExport.insert([CStr(e.p[0]), dxf.codX0])
    stxExport.insert([CStr(e.p[1]), dxf.codY0])
    stxExport.insert(["0", DXF.codZ0])
    stxExport.insert([CStr(e.fParam[0]), "39"])

End

' 100 Subclass marker(AcDbPoint)
'
' 10 Point location( In WCS) DXF: X value; APP: 3 D point
'
' 20, 30 DXF: Y And Z values Of point location( In WCS)
'
' 39 Thickness(Optional ; Default = 0)
'
' 210 Extrusion direction(Optional ; Default = 0, 0, 1) DXF: X value; APP: 3 D vector
'
' 220, 230 DXF: Y And Z values Of extrusion direction(Optional )
'
' 50 Angle Of the X axis For the UCS In effect when the point was drawn(Optional , Default = 0); used when PDMODE Is Nonzero
Public Function ImportDXF(e As Entity, sClaves As String[], sValues As String[]) As Boolean

    Dim i As Integer

    e.P.Clear

    For i = 0 To sClaves.Max

        If sClaves[i] = "10" Then e.P.Add(CFloat(sValues[i]))
        If sClaves[i] = "20" Then e.P.Add(CFloat(sValues[i]))
        ' If sClaves[i] = "30" Then e.P.Add(CFloat(sValues[i]))     'TODO: si vamos a 3D deberia modificar esto

        ' 40 Starting width(Optional ; Default Is 0)
        If sClaves[i] = "40" Then e.fParam[Me.ipaWIdthStart40] = CFloat(sValues[i])

        ' 41 Ending width(Optional ; Default Is 0)
        If sClaves[i] = "41" Then e.fParam[Me.ipaWIdthEnd41] = CFloat(sValues[i])

        ' 42 Bulge(Optional ; Default Is 0).The bulge Is The tangent Of one fourth the included angle For an arc segment, made negative If the arc goes clockwise From the start point To the endpoint.A bulge Of 0 indicates a straight segment, And a bulge Of 1 Is A semicircle

        If sClaves[i] = "42" Then e.fParam[Me.ipaBulge42] = CFloat(sValues[i])

        ' 70 Vertex flags:

        ' 1 = Extra vertex created by curve - fitting
        '
        ' 2 = Curve - fit tangent defined For this vertex.A curve - fit tangent direction Of 0 may be omitted From DXF Output but Is Significant If this bit Is Set
        '
        ' 4 = Not used
        '
        ' 8 = SPLINE vertex created by spline - fitting
        '
        ' 16 = SPLINE frame control point
        '
        ' 32 = 3 D polyline vertex
        '
        ' 64 = 3 D polygon mesh
        '
        ' 128 = Polyface mesh vertex
        If sClaves[i] = "70" Then
            e.fParam[Me.ipaFlags70] = CFloat(sValues[i])
        End If

        ' 50 Curve fit tangent direction

        If sClaves[i] = "50" Then e.fParam[Me.ipaCurveDiection50] = CFloat(sValues[i])

        ' 71 Polyface mesh vertex index(Optional ; present only If nonzero)
        If sClaves[i] = "71" Then e.fParam[Me.ipaMeshIndex1_71] = CFloat(sValues[i])

        ' 72 Polyface mesh vertex index(Optional ; present only If nonzero)
        If sClaves[i] = "72" Then e.fParam[Me.ipaMeshIndex2_72] = CFloat(sValues[i])
        ' 73 Polyface mesh vertex index(Optional ; present only If nonzero)
        If sClaves[i] = "73" Then e.fParam[Me.ipaMeshIndex3_73] = CFloat(sValues[i])        ' 74 Polyface mesh vertex index(Optional ; present only If nonzero)
        If sClaves[i] = "74" Then e.fParam[Me.ipaMeshIndex4_74] = CFloat(sValues[i])
        ' 91 Vertex identifier
        If sClaves[i] = "91" Then e.fParam[Me.ipaIdentifier91] = CFloat(sValues[i])

        ' Every vertex that is part of a polyface mesh has its vertex flag 128 bit set. If the entity supplies the coordinate of a vertex of the mesh, its 64 bit is set as well, and the 10, 20, 30 groups give the vertex coordinate. The vertex index values are determined by the order in which the vertex entities appear within the polyline, with the first being numbered 1.
        '
        ' If the vertex defines a face of the mesh, its vertex flags group has the 128 bit set but not the 64 bit. In this case, the 10, 20, 30 (location) groups of the face entity are irrelevant and are always written as 0 in a DXF file. The vertex indexes that define the mesh are given by 71, 72, 73, and 74 group codes, the values of which specify one of the previously defined vertexes by index. If the index is negative, the edge that begins with that vertex is invisible. The first 0 vertex marks the end of the vertices of the face.

    Next

    'If e.P.Count = 2 Then e.P.Add(0)            ' ensures a 3D point

    Return True

    ' catch

    Return False

End
