' Gambas class file

' Gambas class file

' Gambas class file

' GauchoCAD
' A simple CAD made in Gambas
'
' Copyright (C) Ing Martin P Cristia
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
Create Static

Public Const Gender As String = "Arc_Dimension"
Public Const DrawingOrder As Integer = 100 ' 1 a 32.724 esto debe Drawse primero y ser sobreescrito por el resto
Public Const PointsToDraw As Integer = 1             ' minimal point requered for drawing something usefull
Public Const HelperTrabajo As String = ("Insert a linear acotation")
Public ParamType As String = "PPPP"                             ' that is Point, Point, Float; could be Color Text, etc
Public ParamHelper As String = "Center of arc;First point;Secont point; extension"
Public Const USEWITH As String = "EntityBuilder"
Public Const OrthogonalIgnored As Boolean = False
Public Const OrthogonalForced As Boolean = False
Public Const ParamDefault As String = " "
Public Const StretchAble As Boolean = True           ' Si lo puedo deformar

Public StepsDone As Integer                 ' esto lo cambia cls ElementBuilder durante la construccion

Public TotalDimensions As Integer           ' the total dimensions present in this drawing

' dimstyle: Todas las variables numericas Float estaran multiplicadas por DimScale
Public DimType As Integer = 0            ' = fParam[0] and &X1111
Public DimAtatchPoint As Integer = 2     ' = fParam[1]
Public DimScale As Integer = 1           ' = fParam[2]
Public DimFormat As String = "0.00"      '
Public DimFormatAng As String = "0.0"    '
Public DimArrowSize As Float = 0.3       ' el largo de la flecha
Public DimArrowWidth As Float = 0.1      ' ancho de la flecha
Public DimTickSize As Float = 0.3        ' el tama√±o de la diagonal
Public DimArrowOrThick As Boolean = True ' flecha (True) o diagonal (False)
Public DimTextHeight As Float = 0.3      '
Public DimSeparation As Float = 0.5      ' la separacion entre el punto que define la cota y el inicio de la linea q marca inicio y fin
Public DimExtension As Float = 0.5       ' la continuacion de esas lineas

Public extension As Float
Public iBloque As Integer

' JSON and DXF Read/Export
Public Const JSON_Reading As Boolean = True
Public Const JSON_Export As Boolean = False
Public Const DXF_Reading As Boolean = True
Public Const DXF_Export As Boolean = False

' fParam helpers
Public Const TotalParams As Integer = 8
Public Const ipaEscX As Integer = 0
Public Const ipaEscY As Integer = 1
Public Const ipaEscZ As Integer = 2
Public Const ipaRotacion As Integer = 3
Public Const ipaVertJustif As Integer = 4
Public Const ipaRelativeFactor As Integer = 5
Public Const ipaObliqueAngle As Integer = 6
Public Const ipaExtension As Integer = 7

' stringdata helpers
Public Const sdaTotalParams As Integer = 2
Public Const sdaText As Integer = 0
Public Const sdaStyle As Integer = 1

' Para mejor generalidad y para compatibilidad futura usaremos los P[] asi con los CODE del DXF
' P[] = DXF CODE
' 0 = 10
' 1 = 20
' 2 = 30    Definition points
' 3 = 11
' 4 = 12
' ......
' 20 = 36

' 21 = 210
' 22 = 220	Extrusion direction(Optional ; Default = 0, 0, 1)
' 23 = 230

' fParam[] = DXF CODE
' se usara asi
' 0 =  70, Dimension type:  Values 0 - 6 are integer values that represent the dimension type.Values 32, 64, And 128 are bit values, which are added To the integer values(value 32 Is Always set In R13 And later releases)
'       0 = Rotated; 1 = Aligned; 2 = Angular; 3 = Diameter; 4 = Radius; 5 = Angular3point; 6 = Ordinate
'       32 = Indicates that the block reference(group code 2) Is Referenced by this dimension only
'       64 = Ordinate type.This Is A bit value(bit 7)used only With integer value 6. If set, ordinate Is X - type; If Not set, ordinate Is Y - type
'       128 = This Is A bit value(bit 8)added To the other group 70 values If the dimension text has been positioned at a user - defined location rather than at the Default location
'
' 1 =  71 Attachment point:
'       1 = Top left ; 2 = Top center; 3 = Top right; 4 = Middle left; 5 = Middle center; 6 = Middle right; 7 = Bottom left; 8 = Bottom center; 9 = Bottom right

' 2 = DimScale

' The entity handler receives a user action, and returns the number of expected parameter
' If definitive = true, means the parameter is set
Public Function NewParameter(eBuild As Entity, vParam As Variant[], Optional Definitive As Boolean = False) As Boolean

  ' la linea solo recibe puntos

  If vParam[0] <> "point" Then Return False

  If Me.StepsDone = 0 Then
    Me.DimType = gcd.dimAligned
    clsEntities.setEntity(eBuild)

    Try eBuild.P[0] = vParam[1]
    Try eBuild.P[1] = vParam[2]
    eBuild.P[2] = eBuild.P[0]
    eBuild.P[3] = eBuild.P[1]
    If definitive Then Return True
  Else If Me.StepsDone = 1 Then
    eBuild.DrawAble = True
    eBuild.Finished = True
    Try eBuild.P[2] = vParam[1]
    Try eBuild.P[3] = vParam[2]
    eBuild.P[4] = eBuild.P[2]
    eBuild.P[5] = eBuild.P[3]


    eBuild.pBlock = ReBuildBlock(eBuild)
    If definitive Then Return True
  Else If Me.StepsDone = 2 Then
    eBuild.DrawAble = True
    eBuild.Finished = True
    Try eBuild.P[4] = vParam[1]
    Try eBuild.P[5] = vParam[2]
    eBuild.P[6] = eBuild.P[4]
    eBuild.P[7] = eBuild.P[5]


    eBuild.pBlock = ReBuildBlock(eBuild)
    If definitive Then Return True
  Else If Me.StepsDone = 3 Then
    eBuild.DrawAble = True
    eBuild.Finished = True
    Try eBuild.P[6] = vParam[1]
    Try eBuild.P[7] = vParam[2]


    eBuild.pBlock = ReBuildBlock(eBuild)
    If definitive Then Return True

  Endif


End

Public Sub Translate(e As Entity, dX As Float, dY As Float, Optional OnlySelected As Boolean = False)

  cadInsert.Translate(e, dx, dy, OnlySelected)

End

Public Sub Rotate(e As Entity, radians As Float)

  cadInsert.Rotate(e, radians)

End

Public Sub Scale(e As Entity, sX As Float, sY As Float)

  cadInsert.Scale(e, sx, sy)

End

Public Sub Draw(Optional e As Entity)

  cadInsert.Draw(e)

End

'' A fat version of the entity
Public Sub DrawRemark(oE As Entity)

  cadInsert.DrawRemark(oe)

End

'' A fat version of the entity
Public Sub DrawSelected(oE As Entity)

  cadInsert.DrawSelected(oe)

End

Public Sub ReBuildBlock(ELEM As Entity) As Block

  Dim d As Float, flxTextExt As Float[]
  Dim fRotXY As Float[]

  Dim newBlock As New Block
  Dim f1, f2 As New Float[]



  newBlock.entities = New Entity[]

  ' para definir este bloque necesito 6 entidades
  Dim eLineaPpal As Entity
  Dim eOblique1 As Entity       ' tambien pueden ser flechas Solid
  Dim eOblique2 As Entity
  Dim eExtension1 As Entity
  Dim eExtension2 As Entity
  Dim eDot1 As Entity
  Dim eDot2 As Entity
  Dim eText As Entity
  Dim ePoint2 As Entity

  ' la linea principal ahora es un arco
  clsEntities.Addarc(newBlock.entities, [0, 0], 0, 0, 0, elem.colour, elem.LineWidth, elem.LineType, elem.layerid, newBlock.name)
  eLineaPpal = newBlock.entities.Last

  ' lineas de demarcacion
  clsEntities.AddLine(newBlock.entities, [0, Me.DimExtension, 0, -Me.DimExtension], elem.colour, elem.LineWidth, elem.LineType, elem.layerid, newBlock.name)
  eExtension1 = newBlock.entities.Last

  clsEntities.AddLine(newBlock.entities, [0, Me.DimExtension, 0, -Me.DimExtension], elem.colour, elem.LineWidth, elem.LineType, elem.layerid, newBlock.name)
  eExtension2 = newBlock.entities.Last

  ' flechas


  clsEntities.Addsolid(newBlock.entities, [0, 0, Me.DimArrowSize, Me.DimArrowWidth, Me.DimArrowSize, -Me.DimArrowWidth, 0, 0], elem.colour, elem.LineWidth, elem.LineType, elem.layerid, newBlock.name)
  eOblique1 = newBlock.entities.Last

  clsEntities.Addsolid(newBlock.entities, [0, 0, -Me.DimArrowSize, Me.DimArrowWidth, -Me.DimArrowSize, -Me.DimArrowWidth, 0, 0], elem.colour, elem.LineWidth, elem.LineType, elem.layerid, newBlock.name)
  eOblique2 = newBlock.entities.Last

  ' texto
  clsEntities.AddMText(newBlock.entities, [0, 0, 0, 0], 0, Me.DimTextHeight, "0.00", elem.colour, elem.LineWidth, elem.LineType, elem.layerid, newBlock.name)
  eText = newBlock.entities.Last


  ' -> el bloque
  'iBloque = clsEntities.FIndBlockID(elem.Block)
  elem.fParam[cadInsert.ipaEscX] = 1      ' ScaleX del inserto
  elem.fParam[cadInsert.ipaEscY] = 1      ' ScaleY del inserto
  elem.fParam[cadInsert.ipaEscZ] = 1      ' ScaleY del inserto

  elem.Visible = True


  '
  eLineaPpal.fParam[0] = 0          ' radio
  eLineaPpal.fParam[1] = Ang(elem.P[2] - elem.P[0], elem.P[3] - elem.P[1]) * 180 / Pi

  '
  ' las lineas de extension (las hago HORIZONTALES y las roto)
  eExtension1.P.Clear
  eExtension1.P.Insert([-Me.DimExtension, 0, Me.DimExtension, 0])
  eExtension2.P.Clear
  eExtension2.P.Insert([-Me.DimExtension, 0, Me.DimExtension, 0])

  ' flechas
  eOblique1.P.Clear
  eOblique1.P.Insert([0, 0, -Me.DimArrowWidth, Me.DimArrowSize, Me.DimArrowWidth, Me.DimArrowSize, 0, 0])

  eOblique2.P.Clear
  eOblique2.P.Insert([0, 0, -Me.DimArrowWidth, -Me.DimArrowSize, Me.DimArrowWidth, -Me.DimArrowSize, 0, 0])
  '

  ' 2========================================================================================
  ' nuevo radio
  d = puntos.distancia(elem.P[0], elem.P[1], elem.P[6], elem.P[7])
  eLineaPpal.fParam[0] = d          ' radio del arco

  eLineaPpal.fParam[2] = Ang(elem.P[4] - elem.P[0], elem.P[5] - elem.P[1]) * 180 / Pi
  '

  ' ' la sexta es el texto
  If (eLineaPpal.fParam[2] - eLineaPpal.fParam[1]) < 0 Then eLineaPpal.fParam[2] += 360
  eText.StringData[0] = "L " & Format((eLineaPpal.fParam[2] - eLineaPpal.fParam[1]) / 360 * 2 * puntos.distancia(elem.P[0], elem.P[1], elem.P[4], elem.P[5]) * Pi, Me.DimFormatAng)
  fRotXY = puntos.RotateFromPointWithAngle(elem.P[0], elem.P[1], (eLineaPpal.fParam[2] - eLineaPpal.fParam[1]) / 180 * Pi / 2, elem.P[2], elem.P[3])
  '
  flxTextExt = glPlus.MTextExtends(eText.StringData[cadMText.sdaText], 0, 0, eText.fParam[1])
  '
  eText.P[0] = fRotXY[0] - elem.P[0]
  eText.P[1] = fRotXY[1] - elem.P[1]
  eText.fParam[cadMText.ipaTextAngle] = (eLineaPpal.fParam[2] + eLineaPpal.fParam[1]) / 2 - 90

  ' 3 ===========================================================================



  ' roto
  eExtension1.ClassHandler.Rotate(eExtension1, eLineaPpal.fParam[1] / 180 * Pi)
  eExtension2.ClassHandler.Rotate(eExtension2, eLineaPpal.fParam[2] / 180 * Pi)
  eOblique1.ClassHandler.Rotate(eOblique1, eLineaPpal.fParam[1] / 180 * Pi)
  eOblique2.ClassHandler.Rotate(eOblique2, eLineaPpal.fParam[2] / 180 * Pi)

  ' muevo
  fRotXY = puntos.RotateFromPointWithAngle(elem.P[0], elem.P[1], eLineaPpal.fParam[1] / 180 * Pi, d + elem.P[0], elem.P[1])
  ' traslado una flecha y una linea de extension
  eExtension1.ClassHandler.Translate(eExtension1, fRotXY[0] - elem.P[0], fRotXY[1] - elem.P[1])
  eOblique1.ClassHandler.Translate(eOblique1, fRotXY[0] - elem.P[0], fRotXY[1] - elem.P[1])

  ' muevo
  fRotXY = puntos.RotateFromPointWithAngle(elem.P[0], elem.P[1], eLineaPpal.fParam[2] / 180 * Pi, d + elem.P[0], elem.P[1])
  ' traslado las otras
  eExtension2.ClassHandler.Translate(eExtension2, fRotXY[0] - elem.P[0], fRotXY[1] - elem.P[1])
  eOblique2.ClassHandler.Translate(eOblique2, fRotXY[0] - elem.P[0], fRotXY[1] - elem.P[1])

  ' la sexta es el texto

  fRotXY = puntos.RotateFromPointWithAngle(elem.P[0], elem.P[1], (eLineaPpal.fParam[2] + eLineaPpal.fParam[1]) / 180 * Pi / 2, d + elem.P[0], elem.P[1])

  eText.P[0] = fRotXY[0] - elem.P[0]
  eText.P[1] = fRotXY[1] - elem.P[1]

  ' el largo de la linea principal viene dado por la distancia entre ambos puntos
  d = puntos.distancia(elem.P[0], elem.P[1], elem.P[2], elem.P[3])

  ' con este click calculo el angulo
  'elem.fParam[cadInsert.ipaRotacion] = Ang(elem.p[2] - elem.P[0], elem.p[3] - elem.P[1]) * 180 / Pi

  ' X0

  '===========================================
  Return newBlock


End

Public Function Draw2(oE As Entity)

  cadInsert.Draw2(oe)

End

Public Sub CreatePolygon(oE As Entity)

  cadInsert.CreatePolygon(oe)

End

Public Function BuildPOI(oE As Entity, Optional arrIndex As Integer = -1) As Integer

  cadInsert.BuildPOI(oe, arrIndex)

End

' This function will return False if the element couldn't be created for some reason: bad or incomple user input
' True means all is good, False will instruct the clsEntityBuilder to delete it
Public Sub Finish(oE As Entity) As Boolean

  ' primero agregamos la entidad al array
  BuildPOI(oe)

  ' busco el tipo de linea, si hace falta
  If oE.LineTypeName = "Dashed" Then oE.LineType = 1

  oE.psel.resize(oE.p.count / 2)

  oE.DrawAble = True
  oE.Selected = False
  oE.Finished = True
  'cadInsert.Finish(oe)

End

' Importo los datos que puedo procesar de una coleccion y genero un Entity para ser agregado a un array
Public Function ImportJsonCol(c As Collection, e As Entity) As Boolean

  e.fParam.Resize(Me.TotalParams)


  '     "entity": "ARC_DIMENSION",
  '     "index": 287,
  '     "type": 515,
  '     "handle": [0, 4605],
  '     "size": 1928,
  '     "bitsize": 15276,
  '     "preview_exists": 1,
  '     "reactors": [
  '       [4, 2, 4628, 4628]
  '     ],
  '     "xdicobjhandle": [3, 2, 4618, 4618],
  '     "_subclass": "AcDbEntity",
  '     "prev_entity": [12, 1, 7, 4598],
  '     "next_entity": [10, 1, 125, 4730],
  '     "layer": [5, 2, 5261, 5261],
  '     "preview_exists": 1,
  '     "preview_is_proxy": 0,
  '     "preview_size": 1728,
  '     "preview": "C00600003A0000000C0000001300000000000000880000001D000000000000000000F03F0000000000000000000000000000000000000000000000000000000000000000000000000000F03F0000000000000000000000000000000000000000000000000000000000000000000000000000F03F0000000000000000000000000000000000000000000000000000000000000000000000000000F03F0C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FF7F000054000000200000000200000060E3D71805A97840BCA6894349875F40000000000000000054A146280F1A79404B5AE0861E1A6040000000000000000000000000000000000000000000000000000000000000F03F0C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FF7F00005400000020000000020000001D9441992CA9774084974ED3761F5E4000000000000000004DC7BCD9F23577401AF65059628B5D40000000000000000000000000000000000000000000000000000000000000F03F0C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C0000001400000002000000640000000400000033D53981522A78408F186EB66FC55E400000000000000000E5590ECFB10A304000000000000000000000000000000000000000000000F03F00B59AAB57F72D40903577A1A6EC164000000000000000007FF0BD846EB20840000000000C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FE7F0000540000002000000002000000D62276BBB80F7940D9EB6C67572360400000000000000000DC32B7C1612479400FA018B9E2106040000000000000000000000000000000000000000000000000000000000000F03F0C000000160000000A0000C30C00000017000000FDFFFFFF0C00000012000000FE7F00005400000020000000020000006FA68F83E42B77407C7B366812A05D4000000000000000009DFA3A1605407740B43A634DB7765D40000000000000000000000000000000000000000000000000000000000000F03F0C00000016000000090000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000016000000090000C3A40000000B00000033FA93CF699F7740F2912A141A2E6140000000000000000000000000000000000000000000000000000000000000F03FF8A23A093930EE3F0E6FBFF27E3AD53F000000000000000032362C3137000000050000000100000000000000000000409A9999999999E93F0000000000000000000000000000F03F0000000000000000000000000000000000000000726F6D616E732E736878005C000000C00C00000016000000090000C30C00000017000000FDFFFFFF0C00000012000000000000000C000000140000000200000064000000040000003E4937DCAE7F77405A88857EF1126140000000000000000000E7799EE779FE3F00000000000000000000000000000000000000000000F03F00B3EE5136C0FC3F0075FFDAB537E43F0000000000000000232D4454FB210940000000000C00000016000000020000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000012000000000000000C000000140000000200000054000000200000000200000033D53981522A78408F186EB66FC55E40000000000000000033D53981522A78408F186EB66FC55E40000000000000000000000000000000000000000000000000000000000000F03F0C00000016000000020000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000012000000000000000C000000140000000200000054000000200000000200000047E5E7B604A97840FF04B1AD48875F40000000000000000047E5E7B604A97840FF04B1AD48875F40000000000000000000000000000000000000000000000000000000000000F03F0C00000016000000020000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000012000000000000000C00000014000000020000005400000020000000020000005B7C16FD2CA977401F929A53771F5E4000000000000000005B7C16FD2CA977401F929A53771F5E40000000000000000000000000000000000000000000000000000000000000F03F0C00000016000000020000C30C00000017000000FDFFFFFF0C00000012000000FF7F00000C00000012000000000000000C000000140000000200000054000000200000000200000062797C905E577840C1875C4B165C6140000000000000000062797C905E577840C1875C4B165C6140000000000000000000000000000000000000000000000000000000000000F03F080000001F000000",
  '     "entmode": 2,
  '     "nolinks": 0,
  '     "color": 256,
  '     "ltype_scale": 1.0,
  '     "ltype_flags": 0,
  '     "plotstyle_flags": 0,
  '     "invisible": 0,
  '     "linewt": 29,
  '     "_subclass": "AcDbDimension",
  '     "extrusion": [0.0, 0.0, 1.0],
  '     "text_midpt": [380.92928572639323, 139.3416183844374],
  '     "elevation": 0.0,
  '     "flag1": 11,
  '     "user_text": "",
  '     "text_rotation": 0.0,
  '     "horiz_dir": 0.0,
  '     "ins_scale": [1.0, 1.0, 1.0],
  '     "ins_rotation": 0.0,
  '     "attachment": 5,
  '     "lspace_style": 1,
  '     "lspace_factor": 1.0,
  '     "act_measurement": 26.17270411733045,
  '     "clone_ins_pt": [0.0, 0.0],
  '     "flag": 128,
  '     "_subclass": "AcDbArcDimension",
  '     "def_pt": [389.46058701155391, 138.87772148201296, 0.0],
  '     "xline1_pt": [394.56365099510407, 126.11381094252646, 0.0],
  '     "xline2_pt": [378.5734835508681, 120.49165811629108, 0.0],
  '     "center_pt": [386.64514277068076, 123.08494339705997, 0.0],
  '     "is_partial": 0,
  '     "arc_start_param": 0.36533394824646,
  '     "arc_end_param": 3.45245880810067,
  '     "has_leader": 0,
  '     "leader1_pt": [394.56365099510407, 126.11381094252646, 0.0],
  '     "leader2_pt": [378.5734835508681, 120.49165811629108, 0.0],
  '     "dimstyle": [5, 1, 57, 57],
  '     "block": [5, 2, 4606, 4606]

  e.P.Add(c["center_pt"][0])
  e.P.Add(c["center_pt"][1])

  e.P.Add(c["xline1_pt"][0])
  e.P.Add(c["xline1_pt"][1])

  e.P.Add(c["xline2_pt"][0])
  e.P.Add(c["xline2_pt"][1])

  e.P.Add(c["def_pt"][0])
  e.P.Add(c["def_pt"][1])


  e.fParam[Me.ipaEscX] = 1
  e.fParam[Me.ipaEscY] = 1
  e.fParam[Me.ipaEscZ] = 1

  'e.fParam[Me.ipaRotacion] = CFloat(c["dim_rotation"]) * 180 / Pi

  Dim hBlock As Integer

  e.Block = gcd.CurrDrawing.cmodel["BLOCKS"][c["block"][3]]["block_entity"][3]
  e.pBlock = ReBuildBlock(e)
  'e.Block = gcd.CurrDrawing.arrBlocks[clsEntities.FIndBlockIDbyHandle(hBlock)].name
  ' "block": [5, 2, 3228, 3228] '  esto apunta a cModel["BLOCKS"] , pero hay q buscar otra cosa

  Return True


Catch

  Return False

End
