' Gambas class file

' GambasCAD
' A simple CAD made in Gambas
'
' Copyright (C) Ing Martin P Cristia
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
Create Static
Inherits CadDIMENSION_ANG3PT

Public Const Gender As String = "ARC_DIMENSION"
Public Const DrawingOrder As Integer = 100 ' 1 a 32.724 esto debe Drawse primero y ser sobreescrito por el resto
Public Const PointsToDraw As Integer = 1             ' minimal point requered for drawing something usefull
Public Const CmdLineHelper As String = ("Insert a linear acotation")
Public Const ParamType As String = "PPPP"                             ' that is Point, Point, Float; could be Color Text, etc
Public Const ParamHelper As String = "Center of arc;First point;Secont point;extension"

Public Sub ExportDXFCol(e As Entity, ByRef stxExport As String[]) As Boolean

    cadDimension.ExportDXFCol(e, stxExport)
    stxExport[0] = Me.Gender    ' sobreescribo el nombre de la entidad

    stxExport.insert(["AcDbArcDimension", "100"])
    ' ===========================================================================
    stxExport.insert([CStr(e.p[16]), "13"])
    stxExport.insert([CStr(e.p[17]), "23"])
    stxExport.insert(["0", "33"])

    stxExport.insert([CStr(e.p[18]), "14"])
    stxExport.insert([CStr(e.p[19]), "24"])
    stxExport.insert(["0", "34"])

    stxExport.insert([CStr(e.p[20]), "15"])
    stxExport.insert([CStr(e.p[21]), "25"])
    stxExport.insert(["0", "35"])

    stxExport.insert([CStr(e.p[22]), "16"])
    stxExport.insert([CStr(e.p[23]), "26"])
    stxExport.insert(["0", "36"])

    stxExport.insert([CStr(e.p[24]), "17"])
    stxExport.insert([CStr(e.p[25]), "27"])
    stxExport.insert(["0", "37"])

End

Public Function ImportDXF(e As Entity, sClaves As String[], sValues As String[]) As Boolean

    Dim DimTypeSet As Boolean

    DimTypeSet = False

    cadDimension.ImportDXF(e, sClaves, sValues)

    '
    ' ' en algunos DXF el codigo 70 no esta
    ' If Not DimTypeSet Then gcd.CCC[e.gender] = cadDIMENSION_LINEAR

    ' tengo q presuponer que las escalas son = 1
    e.fParam[Me.ipaEscX] = 1    ' esc X
    e.fParam[Me.ipaEscY] = 1    ' esc Y
    e.fParam[Me.ipaEscZ] = 1    ' esc Z

    ' TODO: cuando este terminada la entidad, sacar eso
    e.pBlock.AbsoluteCoords = True

    ' y poner esto
    ' e.pBlock = Me.ReBuildBlock(e)

    Return True

    '' catch

    Return False

End

'   0 ARC_DIMENSION
'   5 11FD
' 102 {ACAD_REACTORS
' 330 1214
' 102 }
' 102 {ACAD_XDICTIONARY
' 360 120A
' 102 }
' 330 2
' 100 AcDbEntity
'   8 dimmensions
' 160               1764
' 100 AcDbDimension
' 280      0
'   2 *D10
'  10 389.4605870115539
'  20 138.877721482013
'  30 0.0
'  11 380.9292857263932
'  21 139.3416183844374
'  31 0.0
'  70     40
'  71      5
'  42 26.17270411733045
'  73      0
'  74      0
'  75      0
'   3 standard
' 100 AcDbArcDimension
'  13 394.5636509951041
'  23 126.1138109425265
'  33 0.0
'  14 378.5734835508681
'  24 120.4916581162911
'  34 0.0
'  15 386.6451427706808
'  25 123.08494339706
'  35 0.0
'  70      0
'  40 0.3653339482464578
'  41 3.452458808100671
'  71      0
'  16 394.5636509951041
'  26 126.1138109425265
'  36 0.0
'  17 378.5734835508681
'  27 120.4916581162911
'  37 0.0
